# Generated by Django 5.2.4 on 2025-07-07 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sellers", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("return_policy", models.TextField()),
                ("delivery_time", models.CharField(max_length=100)),
                ("shipping_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "max_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum weight in kg",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_policies",
                        to="sellers.seller",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="policies_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Policy",
                "verbose_name_plural": "Shipping Policies",
                "ordering": ["-created_at"],
                "unique_together": {("seller", "title")},
            },
        ),
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "states",
                    models.JSONField(
                        default=list,
                        help_text="List of state/region names covered by this zone",
                    ),
                ),
                ("shipping_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estimated_days",
                    models.PositiveIntegerField(
                        help_text="Estimated delivery time in days"
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="shipping_policies.shippingpolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
