# Generated by Django 5.2.4 on 2025-07-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.CharField(max_length=15)),
                ("customer_address", models.TextField()),
                ("customer_city", models.CharField(max_length=100)),
                ("customer_state", models.CharField(max_length=100)),
                ("customer_pincode", models.CharField(max_length=6)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("length", models.FloatField()),
                ("breadth", models.FloatField()),
                ("height", models.FloatField()),
                ("weight", models.FloatField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("Prepaid", "Prepaid"), ("COD", "Cash on Delivery")],
                        max_length=10,
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15, unique=True)),
                ("business_name", models.CharField(max_length=255)),
                ("business_address", models.TextField(blank=True, null=True)),
                ("gst_number", models.CharField(blank=True, max_length=15, null=True)),
                ("pan_number", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        help_text="Commission rate as percentage (e.g., 15.00 for 15%)",
                        max_digits=5,
                    ),
                ),
                ("pan_document_url", models.URLField(blank=True, null=True)),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("ifsc_code", models.CharField(blank=True, max_length=11, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("is_phone_verified", models.BooleanField(default=False)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("is_document_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="seller_logos/"),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="seller_banners/"
                    ),
                ),
                ("brand_color", models.CharField(blank=True, max_length=7, null=True)),
                (
                    "promotional_codes",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "shipping_methods",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "shipping_days",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "sellers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShippingLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=6)),
                ("phone_number", models.CharField(max_length=15)),
            ],
            options={
                "db_table": "shipping_locations",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=50)),
                ("quantity", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sellers.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_items",
                "ordering": ["-id"],
            },
        ),
    ]
