# Generated by Django 5.1.5 on 2025-05-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinglocation',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='shippinglocation',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippinglocation',
            name='name',
            field=models.CharField(default='Default Location', max_length=100),
        ),
    ]
