# Generated by Django 5.1.5 on 2025-05-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_shippinglocation_country_shippinglocation_is_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinglocation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shippinglocation',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='shippinglocation',
            name='name',
        ),
        migrations.AddField(
            model_name='seller',
            name='pan_document_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
