# Generated by Django 5.2.4 on 2025-07-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("category", "Category"),
                            ("url", "URL"),
                            ("product", "Product"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="offers/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
