# Generated by Django 5.1.6 on 2025-05-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_contactus"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="subject",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
