# Generated by Django 5.2.4 on 2025-07-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("promo_code", models.CharField(max_length=50, unique=True)),
                ("message", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("number_of_users", models.PositiveIntegerField()),
                (
                    "minimum_order_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("discount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed Amount"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("repeat_usage", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(blank=True, null=True, upload_to="promo_images/"),
                ),
                ("list_promo_code", models.BooleanField(default=True)),
                ("used_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
