# Generated by Django 5.1.6 on 2025-02-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='2OU6S35UG3AVRHD6N2ZRE63LCK4TKKZ3', max_length=32),
        ),
    ]
