# Generated by Django 5.2.4 on 2025-07-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="secret",
            field=models.CharField(
                default="5UTX7ZYFX5KUNIXELEWOWIRMMWEKBUQV", max_length=32
            ),
        ),
    ]
