# Generated by Django 5.1.6 on 2025-02-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0002_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='UYHT45OOKYY43VABHHBOMMLA5364WKMP', max_length=32),
        ),
    ]
