# Generated by Django 5.2.4 on 2025-07-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_users", "0002_alter_qrcode_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="secret",
            field=models.CharField(
                default="KM4E5SGWM3O2NSDQHCERQYFZ5ETNMSZR", max_length=32
            ),
        ),
    ]
