# Generated by Django 5.1.6 on 2025-02-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0003_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='GPW3D6HO2REZ2R226F2IWEGZWMJ2SZ4F', max_length=32),
        ),
    ]
