# Generated by Django 5.2.4 on 2025-07-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_users", "0003_alter_qrcode_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="secret",
            field=models.CharField(
                default="DG2B4CCZ25AMIH2J7WLPRVPYEMHK7PUB", max_length=32
            ),
        ),
    ]
