# Generated by Django 5.1.6 on 2025-02-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0004_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='SZLJWBXYFWIG62MN2H647D5DCDSA3HWU', max_length=32),
        ),
    ]
