# Generated by Django 5.1.6 on 2025-03-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0005_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='64EL4HZBA66FQZBXQL7D3RHEOMOL3ALD', max_length=32),
        ),
    ]
