# Generated by Django 5.1.6 on 2025-03-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0006_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='ALTBS4BZX45NOSNRETHKSA6JAWVN6OF2', max_length=32),
        ),
    ]
