# Generated by Django 5.1.6 on 2025-03-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0007_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='T2UKSO5CNQBIWLGBHA2N2OUOX6PSOGXI', max_length=32),
        ),
    ]
