# Generated by Django 5.1.7 on 2025-03-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0008_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='F3R32Q4EOLEOP4RWKQ4W3X4LX66INR2F', max_length=32),
        ),
    ]
