# Generated by Django 5.1.7 on 2025-03-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0009_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='ONAMO64TDXYOZBJGLYKWBVMDUD3KKKT5', max_length=32),
        ),
    ]
