# Generated by Django 5.1.7 on 2025-03-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0010_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='5L4ZAWBSFQSNCBHFNZBI5V6C6LHCTGE3', max_length=32),
        ),
    ]
