# Generated by Django 5.1.7 on 2025-03-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0011_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='FPO22BBOCW5W2O6OSRGHLAQKDB5IKRJS', max_length=32),
        ),
    ]
