# Generated by Django 5.1.7 on 2025-03-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0012_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='OBPGBSQ5UBVNBQTY5OOKCKDTLX73RZQ4', max_length=32),
        ),
    ]
