# Generated by Django 5.1.7 on 2025-03-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0013_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='AE3UETHKEK4IFISV6UMHEESWSJ2P7XBB', max_length=32),
        ),
    ]
