# Generated by Django 5.1.7 on 2025-03-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0014_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='7N3H2ZE2IDRA5LWFIR3E3AKD426SSZ4K', max_length=32),
        ),
    ]
