# Generated by Django 5.1.7 on 2025-04-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0015_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='TOG4D76CSTYUHLXLUGBJXR3XC5ZF7WKI', max_length=32),
        ),
    ]
