# Generated by Django 5.1.7 on 2025-04-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0016_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='RZY6QNGNE7IUKFCQDWUF3ZQWAWH2K4QF', max_length=32),
        ),
    ]
