# Generated by Django 5.1.7 on 2025-04-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0018_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='C36V7Z3YDW7KBDA4RPTZAPXSHVJ4MOZC', max_length=32),
        ),
    ]
