# Generated by Django 5.1.7 on 2025-04-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0019_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='PXGK6FT4E775HSS5ILUBNZLH7X5ZI4AF', max_length=32),
        ),
    ]
