# Generated by Django 5.1.7 on 2025-05-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0020_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='MTVS54PIIKJUAKL3JQKNYFWX5XDEOFGA', max_length=32),
        ),
    ]
