# Generated by Django 5.1.7 on 2025-05-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0021_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='AEDGLWY3AQOTORBFOIYVHWSXZY4NAYDJ', max_length=32),
        ),
    ]
