# Generated by Django 5.1.7 on 2025-05-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0022_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='6SN367JZSMWB5ITGFNRZVCT2MANE2O4U', max_length=32),
        ),
    ]
