# Generated by Django 5.1.7 on 2025-05-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0023_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='3MFXHZW5MUG7V7N36Q4L75YODI226J6X', max_length=32),
        ),
    ]
