# Generated by Django 5.1.7 on 2025-05-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0024_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='7IQL3RYHSP5WSRL7CW2IU762PIFDWFFS', max_length=32),
        ),
    ]
