# Generated by Django 5.1.7 on 2025-05-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0025_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='H4EPLP2NTMBLDT577N7PU7UYUD34P6AH', max_length=32),
        ),
    ]
