# Generated by Django 5.1.7 on 2025-05-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0026_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='GKWCFV7KWCANHHHILFPN36O4OZD77YM7', max_length=32),
        ),
    ]
