# Generated by Django 5.1.7 on 2025-05-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0027_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='P4ET3CU37NJ4LW2RORCAU26WBKBY7OPN', max_length=32),
        ),
    ]
