# Generated by Django 5.1.7 on 2025-05-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0028_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='7OENUD7KQDBZ4N7OVC7WWCG3KNZWFIIX', max_length=32),
        ),
    ]
