# Generated by Django 5.1.7 on 2025-05-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0029_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='6SD2EGQOMXFZOS3OJSAUJP4TRZB3Y7ZI', max_length=32),
        ),
    ]
