# Generated by Django 5.1.7 on 2025-05-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0030_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='XTKI7RUHC7LOQTXWUORRLTLGSS7GTXD4', max_length=32),
        ),
    ]
