# Generated by Django 5.1.7 on 2025-05-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0031_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='Y2U6DL5WKM5V7GLMXSQCVELEUWGKTEC3', max_length=32),
        ),
    ]
