# Generated by Django 5.1.7 on 2025-05-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0032_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='6ESRCSI4XXDGI5MQO2PDBEWCN3XXJ55I', max_length=32),
        ),
    ]
