# Generated by Django 5.1.7 on 2025-05-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0033_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='PTJYYEOJXJNA45ETPRCSZSG6MSVH7IRO', max_length=32),
        ),
    ]
