# Generated by Django 5.1.7 on 2025-05-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0034_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='KQ2NJ5L75ETLREMSRP4IDUYQHTUL23KZ', max_length=32),
        ),
    ]
