# Generated by Django 5.1.7 on 2025-05-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0035_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='RA34H76OD22G3S2FEWXV56WMXY4LMEWB', max_length=32),
        ),
    ]
