# Generated by Django 5.1.5 on 2025-05-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0036_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='NR5ZQ5KURBUHUOZYQMDEG5A6TY27KURR', max_length=32),
        ),
    ]
