# Generated by Django 5.1.5 on 2025-05-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0037_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='ACBJARG6U6MRCRCEPVCYKUSBYRIUXKT3', max_length=32),
        ),
    ]
