# Generated by Django 5.1.5 on 2025-05-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0038_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='RX3HSV2VSZILKL7VCC2ELJFJEXEWLJHQ', max_length=32),
        ),
    ]
