# Generated by Django 5.1.5 on 2025-05-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0039_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='LHVE6KHWZZVRDM4NWQALPY6RWIEF2DSW', max_length=32),
        ),
    ]
