# Generated by Django 5.1.5 on 2025-05-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0040_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='RGT67IGHVFSCNG5J6INV6ASZYDD7PWEK', max_length=32),
        ),
    ]
