# Generated by Django 5.1.5 on 2025-05-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0041_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='2X7SHIEGT7NCLJY4W3B63USAOQ7SJRPF', max_length=32),
        ),
    ]
