# Generated by Django 5.1.5 on 2025-05-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0042_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='EJDY7SP4WRI4WT7POFOJOPNGVFHXJ6QL', max_length=32),
        ),
    ]
