# Generated by Django 5.1.5 on 2025-05-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0044_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='7XTAWRI5ERGVVCDISHJYIE2XAB2AC3LU', max_length=32),
        ),
    ]
