# Generated by Django 5.1.5 on 2025-05-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0045_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='CF4L7VIMB7ZFZZ4IAYQUWPHVIDLQJOCN', max_length=32),
        ),
    ]
