# Generated by Django 5.1.5 on 2025-06-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0046_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='GPZQCF23QYGHKUCPKOMF6QRR6LYU4Y2U', max_length=32),
        ),
    ]
