# Generated by Django 5.1.5 on 2025-06-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0047_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='XNE4C6BLO6K5ZT4HVDHRBWZ3VDAOP2O5', max_length=32),
        ),
    ]
