# Generated by Django 5.1.5 on 2025-06-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0048_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='4K7CNTVXLTZT7PKGEIHIL4GYAGRZJCS6', max_length=32),
        ),
    ]
