# Generated by Django 5.1.5 on 2025-06-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_users', '0049_alter_qrcode_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='secret',
            field=models.CharField(default='OSHHVBOQUINXUDNLNLKTZ24EQPNXVSKW', max_length=32),
        ),
    ]
