# Generated by Django 5.2.4 on 2025-07-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("order_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("returned", "Returned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[("shipping", "Shipping"), ("billing", "Billing")],
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("street", models.CharField(max_length=255)),
                ("area", models.CharField(max_length=255)),
                ("landmark", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("pincode", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(blank=True, max_length=100, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("tax_rate", models.FloatField(blank=True, null=True)),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("final_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("return_quantity", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "delivery_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Delivery charges for information collection",
                        max_digits=10,
                    ),
                ),
                (
                    "listing_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Listing price from your table",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "consumer_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Consumer price from your table",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        help_text="Commission rate as percentage (gets from seller)",
                        max_digits=5,
                    ),
                ),
                (
                    "commission_for_each_seller",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Commission amount for each seller",
                        max_digits=10,
                    ),
                ),
                (
                    "commission_for_each_seller_gst",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="GST on commission amount",
                        max_digits=10,
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=18.0,
                        help_text="GST rate as percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "gst_amount_inclusive",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="GST amount inclusive in the sale",
                        max_digits=10,
                    ),
                ),
                (
                    "amount_seller_receives",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Amount seller receives after commission and GST",
                        max_digits=10,
                    ),
                ),
                (
                    "amount_receives_after_paying",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Amount seller receives after paying all charges",
                        max_digits=10,
                    ),
                ),
                (
                    "claimable_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Claimable amount by seller",
                        max_digits=10,
                    ),
                ),
                (
                    "gst_amount_seller",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="GST amount for seller",
                        max_digits=10,
                    ),
                ),
                (
                    "profit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Profit amount after paying seller",
                        max_digits=10,
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=150.0,
                        help_text="Fixed shipping cost of 150 Rs",
                        max_digits=10,
                    ),
                ),
                (
                    "cod_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="COD charges if payment method is COD",
                        max_digits=10,
                    ),
                ),
                (
                    "commission_calculated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("COD", "Cash on Delivery"),
                            ("PhonePe-UPI", "PhonePe UPI"),
                            ("PhonePe-Wallet", "PhonePe Wallet"),
                            ("PhonePe-Card", "PhonePe Card"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=200)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refund_initiated", "Refund Initiated"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("refund_status", models.CharField(blank=True, max_length=50)),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "phonepe_transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "phonepe_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PAYMENT_INITIATED", "Payment Initiated"),
                            ("PAYMENT_SUCCESS", "Payment Success"),
                            ("PAYMENT_PENDING", "Payment Pending"),
                            ("PAYMENT_DECLINED", "Payment Declined"),
                            ("PAYMENT_ERROR", "Payment Error"),
                            ("PAYMENT_CANCELLED", "Payment Cancelled"),
                            ("PAYMENT_EXPIRED", "Payment Expired"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "payment_instrument",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("payment_url", models.URLField(blank=True, max_length=500, null=True)),
                ("callback_url", models.URLField(blank=True, null=True)),
                ("redirect_url", models.URLField(blank=True, null=True)),
                ("phonepe_response", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RefundDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refund_id", models.CharField(max_length=100)),
                ("refund_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REFUND_INITIATED", "Refund Initiated"),
                            ("REFUND_PENDING", "Refund Pending"),
                            ("REFUND_SUCCESS", "Refund Success"),
                            ("REFUND_FAILED", "Refund Failed"),
                        ],
                        default="REFUND_INITIATED",
                        max_length=50,
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="ShipmentStatusUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                ("status_date", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("activity", models.CharField(blank=True, max_length=255, null=True)),
                ("additional_info", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-status_date"],
            },
        ),
        migrations.CreateModel(
            name="ShippingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="shipmojo", max_length=50)),
                ("tracking_id", models.CharField(blank=True, max_length=100)),
                ("awb_number", models.CharField(blank=True, max_length=100)),
                ("tracking_url", models.URLField(blank=True)),
                ("courier_name", models.CharField(blank=True, max_length=100)),
                (
                    "speed",
                    models.CharField(
                        choices=[("standard", "Standard"), ("express", "Express")],
                        max_length=20,
                    ),
                ),
                ("weight", models.FloatField()),
                ("length", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("pickup_location", models.CharField(max_length=255)),
                ("pickup_scheduled", models.DateTimeField(blank=True, null=True)),
                ("expected_delivery", models.DateTimeField(blank=True, null=True)),
                (
                    "shipping_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=50)),
                ("status_updates", models.JSONField(blank=True, default=list)),
                (
                    "shipmojo_order_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "shipmojo_reference_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "courier_company_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "courier_company_service",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "warehouse_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("lr_number", models.CharField(blank=True, max_length=100, null=True)),
                ("label_url", models.URLField(blank=True, null=True)),
                ("label_data", models.TextField(blank=True, null=True)),
                (
                    "pickup_token_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("status_code", models.CharField(blank=True, max_length=20, null=True)),
                ("shipmojo_response", models.JSONField(blank=True, default=dict)),
                ("courier_assigned", models.BooleanField(default=False)),
                ("courier_assigned_at", models.DateTimeField(blank=True, null=True)),
                ("pickup_scheduled_manually", models.BooleanField(default=False)),
                ("is_return_order", models.BooleanField(default=False)),
                ("return_reason_id", models.IntegerField(blank=True, null=True)),
                ("return_reason_comment", models.TextField(blank=True, null=True)),
                (
                    "customer_request",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "verbose_name": "Shipping Details",
                "verbose_name_plural": "Shipping Details",
            },
        ),
        migrations.CreateModel(
            name="InvoiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("seller_notes", models.TextField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invoice_file",
                    models.FileField(blank=True, null=True, upload_to="invoices/"),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_requests",
                        to="customers.customer",
                    ),
                ),
            ],
        ),
    ]
