# Generated by Django 5.2.4 on 2025-07-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
        ("sellers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller_orders",
                to="sellers.seller",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_orders",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="invoicerequest",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_requests",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="orderaddress",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="products.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="paymentdetails",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="refunddetails",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refunds",
                to="orders.paymentdetails",
            ),
        ),
        migrations.AddField(
            model_name="shippingdetails",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="shippingdetails",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                help_text="Seller associated with this shipment",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sellers.seller",
            ),
        ),
        migrations.AddField(
            model_name="shipmentstatusupdate",
            name="shipping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="orders.shippingdetails",
            ),
        ),
    ]
