# Generated by Django 5.1.6 on 2025-02-25 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='callback_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='payment_instrument',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='payment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='phonepe_status',
            field=models.CharField(blank=True, choices=[('PAYMENT_INITIATED', 'Payment Initiated'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_DECLINED', 'Payment Declined'), ('PAYMENT_ERROR', 'Payment Error'), ('PAYMENT_CANCELLED', 'Payment Cancelled'), ('PAYMENT_EXPIRED', 'Payment Expired')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='phonepe_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='courier_company_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='label_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='manifest_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='pickup_token_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='shiprocket_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='shiprocket_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='status_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='RefundDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(max_length=100)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('REFUND_INITIATED', 'Refund Initiated'), ('REFUND_PENDING', 'Refund Pending'), ('REFUND_SUCCESS', 'Refund Success'), ('REFUND_FAILED', 'Refund Failed')], default='REFUND_INITIATED', max_length=50)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.paymentdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('status_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.shippingdetails')),
            ],
            options={
                'ordering': ['-status_date'],
            },
        ),
    ]
