# Generated by Django 5.1.6 on 2025-03-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_paymentdetails_callback_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
