# Generated by Django 5.1.5 on 2025-06-23 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_invoicerequest'),
        ('products', '0006_recentlyviewedproduct_product_view_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='variant_id',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant'),
        ),
    ]
