# Generated by Django 5.1.6 on 2025-02-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField()),
                ('smtp_username', models.CharField(max_length=255)),
                ('smtp_password', models.CharField(max_length=255)),
                ('use_ssl', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirebaseSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=500)),
                ('project_id', models.CharField(max_length=255)),
                ('messaging_sender_id', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=255)),
                ('auth_domain', models.CharField(max_length=255)),
                ('database_url', models.CharField(max_length=255)),
                ('storage_bucket', models.CharField(max_length=255)),
                ('measurement_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='phonePe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonePeApi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('privacy', 'Privacy Policy'), ('return', 'Return Policy'), ('shipping', 'Shipping Policy'), ('admin', 'Admin Policies'), ('seller', 'Seller Policies')], max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='shipRocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipRocketEmail', models.EmailField(max_length=254)),
                ('shipRocketPassword', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('site_logo', models.ImageField(upload_to='logos/')),
                ('meta_description', models.TextField()),
                ('support_number', models.CharField(max_length=12)),
                ('support_email', models.EmailField(max_length=254)),
                ('copyright_details', models.TextField()),
                ('address', models.CharField(max_length=244)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('invoice_title', models.CharField(max_length=255)),
                ('invoice_copyright_details', models.TextField()),
                ('short_description', models.TextField()),
                ('map_iframe', models.TextField()),
                ('authorized_signatory', models.CharField(max_length=255)),
                ('footer_logo', models.ImageField(upload_to='footers/')),
                ('favicon', models.ImageField(upload_to='favicons/')),
                ('meta_keywords', models.TextField()),
                ('social_media_links_facebook', models.URLField()),
                ('social_media_links_twitter', models.URLField()),
                ('social_media_links_instagram', models.URLField()),
                ('social_media_links_youtube', models.URLField()),
                ('social_media_links_pinterest', models.URLField()),
                ('social_media_links_linkedin', models.URLField()),
                ('primary_color', models.CharField(default='#d03fc0', max_length=7)),
                ('secondary_color', models.CharField(default='#ffbb4e', max_length=7)),
                ('font_color', models.CharField(default='#000000', max_length=7)),
                ('header_font_color', models.CharField(default='#ffffff', max_length=7)),
                ('footer_font_color', models.CharField(default='#ffffff', max_length=7)),
                ('header_font_hover_color', models.CharField(default='#ffbb4e', max_length=7)),
                ('footer_font_hover_color', models.CharField(default='#d03fc0', max_length=7)),
                ('header_background_color', models.TextField(default='background: rgb(0,0,0); background: -moz-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: -webkit-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%);')),
                ('footer_background_color', models.TextField(default='background: rgb(0,0,0); background: -moz-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: -webkit-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%);')),
                ('add_to_cart_hover_color', models.CharField(default='#ffffff', max_length=7)),
                ('favorite_hover_color', models.CharField(default='#ffffff', max_length=7)),
                ('add_to_cart_text_hover_color', models.CharField(default='#d03fc0', max_length=7)),
                ('favorite_text_hover_color', models.CharField(default='#d03fc0', max_length=7)),
                ('add_to_cart_text_color', models.CharField(default='#ffffff', max_length=7)),
                ('favorite_text_color', models.CharField(default='#ffffff', max_length=7)),
                ('add_to_cart_background_color', models.TextField(default='background: rgb(0,0,0); background: -moz-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: -webkit-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%);')),
                ('favorite_background_color', models.TextField(default='background: rgb(0,0,0); background: -moz-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: -webkit-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%);')),
                ('login_register_background_color', models.TextField(default='background: rgb(0,0,0); background: -moz-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: -webkit-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%);')),
            ],
        ),
    ]
