# Generated by Django 5.2.4 on 2025-07-07 09:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BannerSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Section Name")),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("grid", "Grid Layout"),
                            ("full_width", "Full Width Banner"),
                            ("staggered", "Staggered Grid"),
                            ("featured", "Featured Products Banner"),
                        ],
                        default="grid",
                        max_length=20,
                        verbose_name="Section Type",
                    ),
                ),
                (
                    "layout_preset",
                    models.CharField(
                        choices=[
                            ("1_large_2_small", "1 Large + 2 Small"),
                            ("3_equal", "3 Equal Size"),
                            ("2_large_1_small", "2 Large + 1 Small"),
                            ("1_full_width", "Full Width Banner"),
                            ("2_half_width", "Two Half Width"),
                            ("custom", "Custom Layout"),
                        ],
                        default="3_equal",
                        max_length=20,
                        verbose_name="Layout Preset",
                    ),
                ),
                (
                    "custom_css_class",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Custom CSS Class",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Background Color",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Banner Section",
                "verbose_name_plural": "Banner Sections",
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="EmailSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("smtp_host", models.CharField(max_length=255)),
                ("smtp_port", models.IntegerField()),
                ("smtp_username", models.CharField(max_length=255)),
                ("smtp_password", models.CharField(max_length=255)),
                ("use_ssl", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="FirebaseSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=500)),
                ("project_id", models.CharField(max_length=255)),
                ("messaging_sender_id", models.CharField(max_length=255)),
                ("app_id", models.CharField(max_length=255)),
                ("auth_domain", models.CharField(max_length=255)),
                ("database_url", models.CharField(max_length=255)),
                ("storage_bucket", models.CharField(max_length=255)),
                ("measurement_id", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Slide Title")),
                ("description", models.TextField(verbose_name="Slide Description")),
                (
                    "image",
                    models.ImageField(
                        upload_to="hero_slides/", verbose_name="Slide Image"
                    ),
                ),
                (
                    "button_text",
                    models.CharField(max_length=50, verbose_name="Button Text"),
                ),
                (
                    "button_link",
                    models.CharField(max_length=255, verbose_name="Button Link"),
                ),
                (
                    "category",
                    models.CharField(
                        default="FEATURED", max_length=50, verbose_name="Category Label"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hero Slide",
                "verbose_name_plural": "Hero Slides",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="phonePe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phonePeApi", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PickupLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("privacy", "Privacy Policy"),
                            ("return", "Return Policy"),
                            ("shipping", "Shipping Policy"),
                            ("admin", "Admin Policies"),
                            ("seller", "Seller Policies"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="shipRocket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipRocketEmail", models.EmailField(max_length=254)),
                ("shipRocketPassword", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WebSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(max_length=255)),
                ("site_logo", models.ImageField(upload_to="logos/")),
                ("meta_description", models.TextField()),
                ("support_number", models.CharField(max_length=12)),
                ("support_email", models.EmailField(max_length=254)),
                ("copyright_details", models.TextField()),
                ("address", models.CharField(max_length=244)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("zipcode", models.CharField(max_length=10)),
                ("invoice_title", models.CharField(max_length=255)),
                ("invoice_copyright_details", models.TextField()),
                ("short_description", models.TextField()),
                ("map_iframe", models.TextField()),
                ("authorized_signatory", models.CharField(max_length=255)),
                ("footer_logo", models.ImageField(upload_to="footers/")),
                ("favicon", models.ImageField(upload_to="favicons/")),
                ("meta_keywords", models.TextField()),
                ("social_media_links_facebook", models.URLField()),
                ("social_media_links_twitter", models.URLField()),
                ("social_media_links_instagram", models.URLField()),
                ("social_media_links_youtube", models.URLField()),
                ("social_media_links_pinterest", models.URLField()),
                ("social_media_links_linkedin", models.URLField()),
                ("primary_color", models.CharField(default="#d03fc0", max_length=7)),
                ("secondary_color", models.CharField(default="#ffbb4e", max_length=7)),
                ("font_color", models.CharField(default="#000000", max_length=7)),
                (
                    "header_font_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                (
                    "footer_font_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                (
                    "header_font_hover_color",
                    models.CharField(default="#ffbb4e", max_length=7),
                ),
                (
                    "footer_font_hover_color",
                    models.CharField(default="#d03fc0", max_length=7),
                ),
                (
                    "header_background_color",
                    models.TextField(
                        default="background: rgb(0,0,0); background: -moz-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: -webkit-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%);"
                    ),
                ),
                (
                    "footer_background_color",
                    models.TextField(
                        default="background: rgb(0,0,0); background: -moz-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: -webkit-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%);"
                    ),
                ),
                (
                    "add_to_cart_hover_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                (
                    "favorite_hover_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                (
                    "add_to_cart_text_hover_color",
                    models.CharField(default="#d03fc0", max_length=7),
                ),
                (
                    "favorite_text_hover_color",
                    models.CharField(default="#d03fc0", max_length=7),
                ),
                (
                    "add_to_cart_text_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                (
                    "favorite_text_color",
                    models.CharField(default="#ffffff", max_length=7),
                ),
                (
                    "add_to_cart_background_color",
                    models.TextField(
                        default="background: rgb(0,0,0); background: -moz-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: -webkit-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%);"
                    ),
                ),
                (
                    "favorite_background_color",
                    models.TextField(
                        default="background: rgb(0,0,0); background: -moz-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: -webkit-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%);"
                    ),
                ),
                (
                    "login_register_background_color",
                    models.TextField(
                        default="background: rgb(0,0,0); background: -moz-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: -webkit-linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%); background: linear-gradient(117deg, rgba(0,0,0,1) 31%, rgba(247,74,76,1) 72%);"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BannerItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Subtitle"
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Tagline"
                    ),
                ),
                (
                    "vertical_text",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Vertical Text",
                    ),
                ),
                (
                    "discount",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Discount Text",
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Button Text"
                    ),
                ),
                (
                    "cta_link",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Button Link",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="banners/", verbose_name="Banner Image"
                    ),
                ),
                (
                    "grid_column_span",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name="Column Span",
                    ),
                ),
                (
                    "grid_row_span",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name="Row Span",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "text_position",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                            ("top_left", "Top Left"),
                            ("top_right", "Top Right"),
                            ("bottom_left", "Bottom Left"),
                            ("bottom_right", "Bottom Right"),
                            ("custom", "Custom Position"),
                        ],
                        default="center",
                        max_length=20,
                        verbose_name="Text Position",
                    ),
                ),
                (
                    "is_explore_style",
                    models.BooleanField(
                        default=False, verbose_name="Use Explore Style"
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        choices=[
                            ("light", "Light (White)"),
                            ("dark", "Dark (Black)"),
                            ("custom", "Custom Color"),
                        ],
                        default="light",
                        max_length=20,
                        verbose_name="Text Color",
                    ),
                ),
                (
                    "custom_text_color",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Custom Text Color",
                    ),
                ),
                (
                    "overlay_opacity",
                    models.IntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Overlay Opacity (%)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banner_items",
                        to="system_settings.bannersection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banner Item",
                "verbose_name_plural": "Banner Items",
                "ordering": ["display_order"],
            },
        ),
    ]
