# Generated by Django 5.1.7 on 2025-04-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Slide Title')),
                ('description', models.TextField(verbose_name='Slide Description')),
                ('image', models.ImageField(upload_to='hero_slides/', verbose_name='Slide Image')),
                ('button_text', models.CharField(max_length=50, verbose_name='Button Text')),
                ('button_link', models.CharField(max_length=255, verbose_name='Button Link')),
                ('category', models.CharField(default='FEATURED', max_length=50, verbose_name='Category Label')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
