# Generated by Django 5.1.7 on 2025-04-04 16:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Section Name')),
                ('section_type', models.CharField(choices=[('grid', 'Grid Layout'), ('full_width', 'Full Width Banner'), ('staggered', 'Staggered Grid'), ('featured', 'Featured Products Banner')], default='grid', max_length=20, verbose_name='Section Type')),
                ('layout_preset', models.CharField(choices=[('1_large_2_small', '1 Large + 2 Small'), ('3_equal', '3 Equal Size'), ('2_large_1_small', '2 Large + 1 Small'), ('1_full_width', 'Full Width Banner'), ('2_half_width', 'Two Half Width'), ('custom', 'Custom Layout')], default='3_equal', max_length=20, verbose_name='Layout Preset')),
                ('custom_css_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='Custom CSS Class')),
                ('background_color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Background Color')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner Section',
                'verbose_name_plural': 'Banner Sections',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BannerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtitle')),
                ('tagline', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tagline')),
                ('vertical_text', models.CharField(blank=True, max_length=30, null=True, verbose_name='Vertical Text')),
                ('discount', models.CharField(blank=True, max_length=30, null=True, verbose_name='Discount Text')),
                ('cta_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Button Text')),
                ('cta_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Button Link')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Banner Image')),
                ('grid_column_span', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Column Span')),
                ('grid_row_span', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Row Span')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('text_position', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('top_left', 'Top Left'), ('top_right', 'Top Right'), ('bottom_left', 'Bottom Left'), ('bottom_right', 'Bottom Right'), ('custom', 'Custom Position')], default='center', max_length=20, verbose_name='Text Position')),
                ('is_explore_style', models.BooleanField(default=False, verbose_name='Use Explore Style')),
                ('text_color', models.CharField(choices=[('light', 'Light (White)'), ('dark', 'Dark (Black)'), ('custom', 'Custom Color')], default='light', max_length=20, verbose_name='Text Color')),
                ('custom_text_color', models.CharField(blank=True, max_length=20, null=True, verbose_name='Custom Text Color')),
                ('overlay_opacity', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Overlay Opacity (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_items', to='system_settings.bannersection')),
            ],
            options={
                'verbose_name': 'Banner Item',
                'verbose_name_plural': 'Banner Items',
                'ordering': ['display_order'],
            },
        ),
    ]
