# Generated by Django 5.2.4 on 2025-07-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FirestoreMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firestore_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Firestore ID"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="Original Filename"),
                ),
                (
                    "storage_path",
                    models.CharField(max_length=512, verbose_name="Storage Path"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="Content Type"),
                ),
                ("size", models.PositiveIntegerField(verbose_name="File Size")),
                (
                    "directory",
                    models.CharField(max_length=100, verbose_name="Directory"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "thumbnail_path",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Thumbnail Path",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media File",
                "verbose_name_plural": "Media Files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FirestoreProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Is Primary Image"),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Position"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ["position"],
            },
        ),
    ]
