# Generated by Django 5.2.4 on 2025-07-07 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media_management", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="firestoremedia",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="firestore_media_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="firestoreproductimage",
            name="media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="media_management.firestoremedia",
            ),
        ),
        migrations.AddField(
            model_name="firestoreproductimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="firestore_images",
                to="products.product",
            ),
        ),
        migrations.AddIndex(
            model_name="firestoremedia",
            index=models.Index(
                fields=["content_type"], name="media_manag_content_c9383f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="firestoremedia",
            index=models.Index(
                fields=["directory"], name="media_manag_directo_88c1a5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="firestoreproductimage",
            unique_together={("product", "media")},
        ),
    ]
