# Generated by Django 5.1.7 on 2025-05-07 19:14

import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantattribute',
            name='attribute_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Specific price for this attribute (optional)', max_digits=10, null=True, validators=[products.validators.validate_price]),
        ),
    ]
