# Generated by Django 5.2.4 on 2025-07-07 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0002_initial"),
        ("customers", "0002_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brands_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brands_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_cart_items",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.brand",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="categories.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_cart_items",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productfeaturerequest",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_requests",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productfeaturerequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_feature_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productfeaturerequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_product_feature_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productreview",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productstock",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_entries",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productvideo",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="recentlyviewedproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recent_views",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="recentlyviewedproduct",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recently_viewed_products",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="recentlyviewedproduct",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recent_views",
                to="products.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="variantattribute",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_attributes",
                to="products.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_wishlist_items",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_wishlist_items",
                to="customers.customer",
            ),
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(fields=["slug"], name="products_br_slug_d4d839_idx"),
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(fields=["name"], name="products_br_name_0925fd_idx"),
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(
                fields=["is_active"], name="products_br_is_acti_297ee1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="products_pr_slug_3edc0c_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="products_pr_sku_ca0cdc_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="products_pr_categor_9edb3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["brand"], name="products_pr_brand_i_dc6890_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "status"], name="products_pr_is_acti_a04283_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="products_pr_created_bce1a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["shipping_policy_id"], name="products_pr_shippin_51a229_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["order_id", "product"], name="products_or_order_i_d711b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["-created_at"], name="products_or_created_2fe3b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["user", "product"], name="products_ca_user_id_3aeb92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["-created_at"], name="products_ca_created_6ec652_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("user", "product", "variant_id")},
        ),
        migrations.AddIndex(
            model_name="productattribute",
            index=models.Index(
                fields=["product", "attribute_type", "value"],
                name="products_pr_product_3db264_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "is_primary", "sort_order"],
                name="products_pr_product_7d975c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["color_attribute"], name="products_pr_color_a_1f2bad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["product", "is_approved"], name="products_pr_product_160d92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["-created_at"], name="products_pr_created_cdd17c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together={("product", "user")},
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product", "sku"], name="products_pr_product_b3af96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["is_active"], name="products_pr_is_acti_9d6315_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["variant_slug"], name="products_pr_variant_a79dc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["-view_count"], name="products_pr_view_co_51d29e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["-last_viewed_at"], name="products_pr_last_vi_59d747_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "sku")},
        ),
        migrations.AddIndex(
            model_name="productvideo",
            index=models.Index(
                fields=["product", "is_featured", "sort_order"],
                name="products_pr_product_27a8a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recentlyviewedproduct",
            index=models.Index(
                fields=["-viewed_at"], name="products_re_viewed__5e81d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recentlyviewedproduct",
            index=models.Index(fields=["user"], name="products_re_user_id_09686c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="recentlyviewedproduct",
            unique_together={("user", "product")},
        ),
        migrations.AddIndex(
            model_name="variantattribute",
            index=models.Index(
                fields=["variant", "attribute_type", "value"],
                name="products_va_variant_0822d0_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="variantattribute",
            unique_together={("variant", "attribute_type")},
        ),
        migrations.AddIndex(
            model_name="wishlistitem",
            index=models.Index(
                fields=["user", "product"], name="products_wi_user_id_ed2b89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wishlistitem",
            index=models.Index(
                fields=["-created_at"], name="products_wi_created_5b4214_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wishlistitem",
            unique_together={("user", "product")},
        ),
    ]
