# Generated by Django 5.1.7 on 2025-05-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_variantattribute_attribute_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_description',
            field=models.TextField(blank=True, help_text='Optional additional product description or features', null=True),
        ),
    ]
