# Generated by Django 5.1.7 on 2025-05-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_additional_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
