# Generated by Django 5.1.5 on 2025-05-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_additional_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_storage_path',
            field=models.CharField(blank=True, help_text='Firebase Storage path for logo', max_length=255, null=True),
        ),
    ]
