# Generated by Django 5.1.5 on 2025-05-28 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_contactus_subject'),
        ('products', '0005_brand_logo_storage_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productstock',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productstock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['variant_slug'], name='products_pr_variant_a79dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['-view_count'], name='products_pr_view_co_51d29e_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['-last_viewed_at'], name='products_pr_last_vi_59d747_idx'),
        ),
        migrations.AddField(
            model_name='recentlyviewedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_views', to='products.product'),
        ),
        migrations.AddField(
            model_name='recentlyviewedproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_products', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='recentlyviewedproduct',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recent_views', to='products.productvariant'),
        ),
        migrations.AddIndex(
            model_name='recentlyviewedproduct',
            index=models.Index(fields=['-viewed_at'], name='products_re_viewed__5e81d2_idx'),
        ),
        migrations.AddIndex(
            model_name='recentlyviewedproduct',
            index=models.Index(fields=['user'], name='products_re_user_id_09686c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recentlyviewedproduct',
            unique_together={('user', 'product')},
        ),
    ]
