# Generated by Django 5.1.5 on 2025-06-23 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_categoryrequest'),
        ('products', '0006_recentlyviewedproduct_product_view_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shipping_policy_id'], name='products_pr_shippin_51a229_idx'),
        ),
    ]
